using System.Reflection;
using System.Runtime.InteropServices;

// The usual assembly metadata. Nothing exciting here.
// This file is generated by Visual Studio and then immediately forgotten about
// until someone needs to know the assembly version and finds it hardcoded in three other places.
[assembly: AssemblyTitle("BikeRental")]
[assembly: AssemblyDescription("A bike rental web application built on .NET 4.8 and ASP.NET Web API 2.")]
[assembly: AssemblyCompany("PedalPal")]
[assembly: AssemblyProduct("BikeRental")]
[assembly: AssemblyCopyright("Copyright © PedalPal 2008")]
[assembly: ComVisible(false)]
[assembly: Guid("9e1c4f32-7b8a-4d6e-a2b5-3f7c8e9d1a2b")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
